### ISSUE TITLE
What happens if an user has lost their authenticator account?

### ISSUE THREAD

**Issue by cssquirrel** [Offroadcode/Umbraco-2FA#1]
How does a user set up a new authenticator account if they've lost theirs? I assume this would require admin assistance. A question for @steroberts89.

**Comment by cssquirrel** [comment]
We have added the ability for admin users to remove 2FA from specific users.

**Comment by fiftynineseconds** [comment]
Hi - How do admin users do that?

**Comment by dstream** [comment]
@fiftynineseconds admin can't do that currently, you have to update your database directly, set FortressUser2FASettings.FortressUser2FASettings field to False

**Comment by fiftynineseconds** [comment]
@dstream Thanks!
