### ISSUE TITLE
Make 2fa mandatory for all users

### ISSUE THREAD

**Issue by liranp1** [Offroadcode/Umbraco-2FA#17]
hi, i would like to ask i you could make 2fa mandatory for all users.
i have alot of users because multiple sites and i want all of them to have to use 2fa.

thanks

**Comment by ng-soft** [comment]
This is a little complicate. What you have to do is to create another role of unauthorized that can access only to the page with the 2fa setup process, after the user will activate his 2fa you need to change programmly  his role to the regular role and to allow him all the other pages.

**Comment by liranp1** [comment]
ok, 10x
