### ISSUE TITLE
Implement the SMS provider

### ISSUE THREAD

**Issue by JeffreyPerplex** [Offroadcode/Umbraco-2FA#6]
I tried to register my own SMS Provider. I will sent a Pull Request later on, when I've got it to work, but for now the implementation is hidden in an internal class.

I've implemented your BaseSMSPRovider-class with the following code:

`using PerplexLibSMS.Interfaces;
using PerplexLibSMS.SMSApis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _2FA.Code
{
    public class TwoFactorSMSPerplexProvider : Orc.Fortress.SMSProvider.BaseSMSProvider
    {
        public override void SendSms(string number, string message)
        {
            ISMSApi api = new CMProvider();
            api.From = "+31263830734";
            api.To = new List<string>() {number}; 
            var result = api.Send(message);

        }
    }
}`

But then what? I expected that maybe in Umbraco the dropdownlist with "Active SMS Providers" would contain "TwoFactorSMSPerplexProvider" or something like that. Also I tried to set a value like 'TwoFactorSMSPerplexProvider' into the table FortressSettings but that didn't work either.

Can you help me out?

Thanks, Jeffrey

**Comment by PeteDuncanson** [comment]
We are encouraging folks to not use SMS as its insecure (well sort of) so we've been using Authenticator by Google.

Will need to get @steroberts89 to write up a little doc on how to create providers as its his black magic that does that bit and its all in his head :)

**Comment by cssquirrel** [comment]
I've created a new issue, #9, to cover the need for documentation on how to extend functionality. I'm going to close this issue as *wontfix*, though, as we won't be implementing an SMS provider ourselves.
