### ISSUE TITLE
Cannot install on Umbraco 7.8.1

### ISSUE THREAD

**Issue by LeighYuill** [Offroadcode/Umbraco-2FA#8]
Hi, 
I am trying to install this package on Umbraco 7.8.1 and it seems to crash on the install but does not show an error message. Then when I view the site it gives the error message...
![2fa-install-error](https://user-images.githubusercontent.com/4311577/36594581-a7eddce0-1896-11e8-9c1a-3f99041b845c.png)

I have seen the note on the [Umbraco package page](https://our.umbraco.org/projects/backoffice-extensions/umbraco-2fa/) saying do not install on versions 7.7 and above but it also said that the [GitHub page](https://github.com/Offroadcode/Umbraco-2FA) is more up to date, which says 7.6+ is fine.

Is this the error the Umbraco package page is referring too, or am I doing something wrong?

Thanks,

**Comment by cssquirrel** [comment]
@LeighYuill At present we don't have an update to the package for it to operate in Umbraco 7.8+ yet. As such, I can only recommend it's use on 7.6. We're actively looking into support in 7.8 however, so I'll comment again on this issue once I have more to report.

**Comment by LeighYuill** [comment]
:) Thank you for clarifying. I did think this was the case but wanted to double check I wasn't mistaken.

Thanks.

**Comment by steroberts89** [comment]
@LeighYuill I've just pushed a "pre-release" https://github.com/Offroadcode/Umbraco-2FA/releases/tag/
Could you try this on your installation? I've tested it on 7.7,7.8 and 7.9

**Comment by LeighYuill** [comment]
Thank you for this. Sorry for the late reply, I will try it out next week and feed back.

Thanks again.

**Comment by SteveEdson** [comment]
Just done some further digging, I get a response with the QR code, I can browse to this manually and scan it.

When I added the code I received an error message, I tried again once the code refreshed and it appeared to send two network requests. The first came back saying `isValid: true`, the second had a 500 error saying that my account has already been set up.

I'm also getting issues where my session keeps expiring after ~20 seconds with this package installed. When I tried to sign in again, I got the authenticator prompt and the code worked successfully. However, when I go back to the tab, it still says that my account needs to be set up. This obviously generates another 500 when I click the `[general_setup]` button, saying that my account *has* been set up.

**Comment by SteveEdson** [comment]
More digging:

The logout issue is triggered by the error:

```
ERROR Umbraco.Web.WebApi.Filters.AngularAntiForgeryHelper - Could not validate XSRF token
System.Web.Mvc.HttpAntiForgeryException (0x80004005): The provided anti-forgery token was meant for user "test@test.com", but the current user is "".
   at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext, String cookieToken, String formToken)
   at System.Web.Helpers.AntiForgery.Validate(String cookieToken, String formToken)
   at Umbraco.Web.WebApi.Filters.AngularAntiForgeryHelper.ValidateTokens(String cookieToken, String headerToken)
```

This happens randomly when clicking between the same pages, e.g switching between the media and content menus.
